# Generated by Django 4.1.7 on 2023-03-23 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('idtema', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_tema', models.CharField(max_length=45)),
                ('foto_tema', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'tema',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Postagen',
            fields=[
                ('idpostagen', models.OneToOneField(db_column='idpostagen', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='blogapp.tema')),
                ('nome_post', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'postagen',
                'managed': False,
            },
        ),
    ]
